[package]
name = "tiny-os"
version = "0.1.0"
edition = "2018"
authors = ["Cedric Chee <cedric+gh@invictusbyte.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.8"